### ISSUE TITLE
Code update

### ISSUE THREAD

**Issue by bigretromike** [skeptical/jumpy#2]
Is there a change for update source code ?:-) as the development version is higher than this - or is there dev source code available somewhere else ?

**Comment by skeptical** [comment]
Sorry, I haven't ever pushed the dev branch(es) to github, fixed now.  Note that the Kodi plugin source is not here, but at [jumpy-xbmc](https://github.com/skeptical/jumpy-xbmc) :-).

**Comment by bigretromike** [comment]
Im hoping to look into both :-) also thanks for update

**Comment by skeptical** [comment]
PRs are welcome too :-).

**Comment by bigretromike** [comment]
Sure if i will be able to do something that help your project

On October 21, 2016 3:19:15 PM GMT+02:00, skeptical notifications@github.com wrote:

> PRs are welcome too :-).
> 
> ## 
> 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/skeptical/jumpy/issues/2#issuecomment-255374391

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.
